# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
    healthcheck:
      #test: ["CMD", "curl", "-f", "https://survey-analysis-rag.onrender.com/docs"]
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    environment:
      #- NEXT_PUBLIC_BACKEND_URL=https://survey-analysis-rag.onrender.com:8000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://survey-analysis-rag.vercel.app/"]
      #test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge